steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-central2-docker.pkg.dev/gcp-deploy-492010/vetmed/api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
images:
  - 'europe-central2-docker.pkg.dev/gcp-deploy-492010/vetmed/api:latest'
