@startuml VetMed-PrzypadkiUzycia
title VetMed — Diagram przypadków użycia

left to right direction
skinparam shadowing false
skinparam packageStyle rectangle

actor "Właściciel\nzwierzęcia" as Owner
actor "Lekarz /\npersonel kliniki" as Vet

rectangle "System VetMed" {
  usecase "Rejestracja konta" as UC1
  usecase "Logowanie" as UC2
  usecase "Zarządzanie zwierzętami\n(dodaj / edytuj / archiwizuj)" as UC3
  usecase "Umówienie wizyty" as UC4
  usecase "Przegląd historii leczenia" as UC5
  usecase "Przegląd powiadomień" as UC6

  usecase "Zarządzanie wizytami\n(potwierdź / odrzuć / zakończ)" as UC7
  usecase "Prowadzenie kartoteki\n(szczepienia, recepty)" as UC8
  usecase "Zarządzanie grafikiem\ndostępności" as UC9
}

Owner --> UC1
Owner --> UC2
Owner --> UC3
Owner --> UC4
Owner --> UC5
Owner --> UC6

Vet --> UC2
Vet --> UC7
Vet --> UC8
Vet --> UC9

UC4 ..> UC2 : <<include>>
UC3 ..> UC2 : <<include>>

@enduml
